version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: foodgram_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: andreipetrov94/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/app/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: andreipetrov94/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/app/frontend_static

  gateway:
    image: andreipetrov94/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
    depends_on:
      - frontend
      - backend