MAX_LENGTH_EMAILFIELD = 254
MAX_LENGTH_CHARFIELD_NAME = 150
MAX_LENGTH_CHARFIELD_PASSWORD = 150

MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32

MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64

MAX_LENGTH_RECIPE_NAME = 256

MIN_VALUE_COOKING_TIME = 1
