# Generated by Django 3.2.16 on 2025-03-04 12:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250302_1618'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='taboo_self_follow',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), _negated=True), name='taboo_self_follow'),
        ),
    ]
